Fix lifecycle

diff --git a/todo-backend/.s2i/bin/assemble b/todo-backend/.s2i/bin/assemble
--- a/todo-backend/.s2i/bin/assemble
+++ b/todo-backend/.s2i/bin/assemble
@@ -1,41 +1,14 @@
 #!/bin/bash
 
-set -e
+echo "Performing the S2I build..."
 
-source ${HTTPD_CONTAINER_SCRIPTS_PATH}/common.sh
+#TODO: add call to the standard S2I assemble script
+/usr/libexec/s2i/assemble
+rc=$?
 
-echo "---> Enabling s2i support in httpd24 image"
-
-config_s2i
-
-######## CUSTOMIZATION STARTS HERE ############
-
-echo "---> Installing application source"
-cp -Rf /tmp/src/*.html ./
-
-DATE=`date "+%b %d, %Y @ %H:%M %p"`
-
-echo "---> Creating info page"
-echo "Page built on $DATE" >> ./info.html
-echo "Proudly served by Apache HTTP Server version $HTTPD_VERSION" >> ./info.html
-
-######## CUSTOMIZATION ENDS HERE ############
-
-if [ -d ./httpd-cfg ]; then
-  echo "---> Copying httpd configuration files..."
-  if [ "$(ls -A ./httpd-cfg/*.conf)" ]; then
-    cp -v ./httpd-cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-    rm -rf ./httpd-cfg
-  fi
+if [ $rc -eq 0 ]; then
+    echo "Recording successful build on the life cycle management system..."
 else
-  if [ -d ./cfg ]; then
-    echo "---> Copying httpd configuration files from deprecated './cfg' directory, use './httpd-cfg' instead..."
-    if [ "$(ls -A ./cfg/*.conf)" ]; then
-      cp -v ./cfg/*.conf "${HTTPD_CONFIGURATION_PATH}"
-      rm -rf ./cfg
-    fi
-  fi
+    echo "Not calling the life cycle management system: S2I build failed!"
 fi
-
-# Fix source directory permissions
-fix-permissions ./
+exit $rc
